### ISSUE TITLE
"1:購入"での気になる点

### ISSUE THREAD

**Issue by shunya-miyauchi** [ryoyahoriuchi/object_orientation#40]
- [x] 購入の方で商品価格を確認できない。
→選択肢に"商品一覧"を追加し、価格を確認できるようにする。
- [x] お金が入っていなくても"3:購入する"に進めてしまう。

**Comment by ryoyahoriuchi** [comment]
内容承知しました。
修正するにあたり「お金が入っていなくても"3:購入する"に進めてしまう」の
仕様について確認させてください。下記2点の実装でよろしいでしょうか？

```
- 3:購入するを実行する場合、お金が入っていなければchoiceメソッドへ戻る
- お金が入っていても購入できなければ（金額不足または在庫不足）choiceメソッドへ戻る
```

**Comment by shunya-miyauchi** [comment]
ありがとうございます。
自分は問題ないかと思います。
よろしくお願いします。

**Comment by fumtas1k** [comment]
そうですね、purchaseメソッドで、purchasable_listが空ならchoiceに戻す設定で良いと思います。

**Comment by fumtas1k** [comment]
あと、purchasable_listの仕様変更しましょうか？
purchasable_listに金額を入れたほうが良いってことですよね？

**Comment by shunya-miyauchi** [comment]
たしかに金額も入っていた方が良さそうですね。
