### ISSUE TITLE
# additionメソッドのリファクタリング

### ISSUE THREAD

**Issue by fumtas1k** [ryoyahoriuchi/object_orientation#42]
@juice_manager.exist?(juice)を2回使用している。
1回で、priceに値を代入することが可能なため、if文を1回使用して、そこで、priceに値を代入してしまうことを提案。
（説明がわかりにくいと思うので、購入の部分の修正が終わったらtakaseがやります）

**Comment by shunya-miyauchi** [comment]
ありがとうございます。
その部分思いつかずで、お願いできるとです。
