### ISSUE TITLE
# irbでの可読性向上

### ISSUE THREAD

**Issue by shunya-miyauchi** [ryoyahoriuchi/object_orientation#45]
・ irb上で可読性をあげるために文字色を変えることを提案。
　例）
　「何をしますか？」など質問部分だけ文字を赤色に変更する
　[方法] 別ファイルcolor.rbを作成、文字色を赤にするモジュールを定義し、Stringクラスにミックスイン。

※問題なければ、リファクタリング後に自分が作成します。

**Comment by ryoyahoriuchi** [comment]
良いと思います。
#44のリファクタリングにて一部irbの可読性がよくなると考えアンダーラインを
勝手ながら追記しました。不要であれば削除しますのでご意見をお聞かせください。

**Comment by shunya-miyauchi** [comment]
承知しました。
マージ後に、一度確認してみます。
